@startuml
'!include <plantuml/er_style.puml>

' Определение сущностей
entity "Справочник.Соединения" as Connections {
  --
  Активно : булево
  Адрес : строка
}

entity "Справочник.Соединения.Состав" as ConnectionComposition {
  Активно : булево
  --
  ТипОбъекта : строка
  --
  УсловиеВыгрузки : строка
  --
  Топик : строка
  --
  Группа : строка
  --
  НаправлениеОбмена : ссылка
}

entity "Перечисление.НаправленияОбмена" as ExchangeDirections {
  Значение : enum {Отправка, Получение}
}

entity "Документ.ЗаказКлиента" as SalesOrder {
}

entity "РегистрСведений.СообщенияКОтправке" as MessagesToSend {
  Соединение : Ссылка
  Объект : Ссылка
  Топик : строка
  ИдентификаторЗаписи : GUID
  --
  Обработано : булево
  ДатаОбработки : дата
}

' Связи
Connections -- ConnectionComposition : "содержит"
ConnectionComposition -- ExchangeDirections : "реквизит "Направлениеобмена""
MessagesToSend -- Connections : "измерение "Соединение""
MessagesToSend -- SalesOrder : "измерение "Объект""

' Примечание о происхождении топика note right of MessagesToSend : Измерение "Топик" регистра\nсоответствует реквизиту "Топик"\nв табличной части "Состав"

@enduml